###Load the data

In [18]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("ibrohimsharipov/12-months-sales-data")

print("Path to dataset files:", path)

Using Colab cache for faster access to the '12-months-sales-data' dataset.
Path to dataset files: /kaggle/input/12-months-sales-data

In [19]:
import pandas as pd
import os

# Get the path to the downloaded dataset files
path = '/root/.cache/kagglehub/datasets/ibrohimsharipov/12-months-sales-data/versions/1'

# List all files in the directory
all_files = [os.path.join(path, f) for f in os.listdir(path) if f.endswith('.csv')]

# Read and concatenate all CSV files into a single DataFrame
df_list = []
for file in all_files:
    df_list.append(pd.read_csv(file))

df = pd.concat(df_list, ignore_index=True)

# Display the first few rows of the combined DataFrame
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,194095,Wired Headphones,1,11.99,05/16/19 17:14,"669 2nd St, New York City, NY 10001"
1,194096,AA Batteries (4-pack),1,3.84,05/19/19 14:43,"844 Walnut St, Dallas, TX 75001"
2,194097,27in FHD Monitor,1,149.99,05/24/19 11:36,"164 Madison St, New York City, NY 10001"
3,194098,Wired Headphones,1,11.99,05/02/19 20:40,"622 Meadow St, Dallas, TX 75001"
4,194099,AAA Batteries (4-pack),2,2.99,05/11/19 22:55,"17 Church St, Seattle, WA 98101"

###Drop rows with missing values

In [20]:
# Drop rows where 'Order Date' is 'Order Date' (which indicates a header row)
df = df[df['Order Date'] != 'Order Date']

# Drop rows with missing values in the relevant columns
df.dropna(subset=['Quantity Ordered', 'Price Each'], inplace=True)
df.columns

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address'],
      dtype='object')

###converte columns like **'Quantity Ordered'** and **'Price Each'** from String to numeric datatype

In [21]:
df['Quantity Ordered'] = pd.to_numeric(df['Quantity Ordered'])
df['Price Each'] = pd.to_numeric(df['Price Each'])

df[['Quantity Ordered', 'Price Each']].dtypes

Quantity Ordered      int64
Price Each          float64
dtype: object

####Creating a new **'Total Sale'** column by multiplying the ***'Quantity Ordered'*** column by the ***'Price Each'*** column

In [22]:
df['Total Sales'] = df['Quantity Ordered'] * df['Price Each']
display(df.head())

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Total Sales
0,194095,Wired Headphones,1,11.99,05/16/19 17:14,"669 2nd St, New York City, NY 10001",11.99
1,194096,AA Batteries (4-pack),1,3.84,05/19/19 14:43,"844 Walnut St, Dallas, TX 75001",3.84
2,194097,27in FHD Monitor,1,149.99,05/24/19 11:36,"164 Madison St, New York City, NY 10001",149.99
3,194098,Wired Headphones,1,11.99,05/02/19 20:40,"622 Meadow St, Dallas, TX 75001",11.99
4,194099,AAA Batteries (4-pack),2,2.99,05/11/19 22:55,"17 Church St, Seattle, WA 98101",5.98