###Load the data

In [ ]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("skmewati/myntra-sales-dataset")

print("Path to dataset files:", path)

Downloading from https://www.kaggle.com/api/v1/datasets/download/skmewati/myntra-sales-dataset?dataset_version_number=1...

100%|██████████| 403k/403k [00:00<00:00, 69.1MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/skmewati/myntra-sales-dataset/versions/1

In [ ]:
import pandas as pd
df=pd.read_csv(path+"/myntra_dataset_ByScraping.csv")
df.head()

,brand_name,pants_description,price,MRP,discount_percent,ratings,number_of_ratings
0,WROGN,Men Loose Fit Cotton Jeans,1374.0,2499.0,0.45,4.2,57.0
1,Flying Machine,Men Slim Fit Jeans,1829.0,2999.0,0.39,4.6,5.0
2,Roadster,Men Pure Cotton Jeans,974.0,2499.0,0.61,3.6,1100.0
3,Bene Kleed,Relaxed Fit Denim Jeans,873.0,2299.0,0.62,4.0,4800.0
4,Levis,Men 511 Slim Fit Jeans,1478.0,2899.0,0.49,4.3,264.0

###Select a text column and applying lowercasing to standardize the text

In [ ]:
df['pants_description'] = df['pants_description'].str.lower()
df.head()

,brand_name,pants_description,price,MRP,discount_percent,ratings,number_of_ratings
0,WROGN,men loose fit cotton jeans,1374.0,2499.0,0.45,4.2,57.0
1,Flying Machine,men slim fit jeans,1829.0,2999.0,0.39,4.6,5.0
2,Roadster,men pure cotton jeans,974.0,2499.0,0.61,3.6,1100.0
3,Bene Kleed,relaxed fit denim jeans,873.0,2299.0,0.62,4.0,4800.0
4,Levis,men 511 slim fit jeans,1478.0,2899.0,0.49,4.3,264.0

###Remove a common but uninformative word, such as **"men's,"** from the text to clean it further

In [ ]:
df['pants_description'] = df['pants_description'].str.replace("men's", "")
df.head()

,brand_name,pants_description,price,MRP,discount_percent,ratings,number_of_ratings
0,WROGN,men loose fit cotton jeans,1374.0,2499.0,0.45,4.2,57.0
1,Flying Machine,men slim fit jeans,1829.0,2999.0,0.39,4.6,5.0
2,Roadster,men pure cotton jeans,974.0,2499.0,0.61,3.6,1100.0
3,Bene Kleed,relaxed fit denim jeans,873.0,2299.0,0.62,4.0,4800.0
4,Levis,men 511 slim fit jeans,1478.0,2899.0,0.49,4.3,264.0